import pytest
import os
import tempfile
from unittest.mock import patch, MagicMock
from app.services.pdf_service import (
    course_json_to_markdown,
    markdown_to_html,
    save_pdf_file,
    generate_course_pdf
)


class TestPDFService:
    """Test cases for PDF generation service"""

    def setup_method(self):
        """Setup method run before each test"""
        # Create a mock course data for testing
        self.mock_course_data = {
            "course_id": "test_course_123",
            "title": "Python Programming Basics",
            "description": "Learn Python programming from scratch",
            "difficulty": "beginner",
            "language": "english",
            "duration_weeks": 4,
            "learning_objectives": [
                "Understand Python syntax",
                "Learn data structures",
                "Master control flow",
                "Build simple applications"
            ],
            "prerequisites": ["Basic computer knowledge"],
            "weeks": [
                {
                    "week_number": 1,
                    "title": "Python Basics",
                    "objectives": ["Learn variables", "Understand data types"],
                    "days": [
                        {
                            "day_number": 1,
                            "title": "Introduction to Python",
                            "objectives": ["Install Python", "Write first program"],
                            "content": "Python is a high-level programming language...",
                            "activities": ["Install Python", "Write Hello World program"]
                        }
                    ]
                }
            ],
            "assignments": [
                {
                    "title": "Python Basics Quiz",
                    "type": "MCQ",
                    "difficulty": "beginner",
                    "questions": ["What is Python?", "How to install Python?"],
                    "solutions": ["Answer 1", "Answer 2"]
                }
            ],
            "flashcards": [
                {
                    "front": "What is Python?",
                    "back": "Python is a high-level programming language",
                    "category": "Concept"
                }
            ],
            "created_at": "2024-01-01T00:00:00Z"
        }

    def test_course_json_to_markdown_basic(self):
        """Test basic JSON to Markdown conversion"""
        markdown_content = course_json_to_markdown(self.mock_course_data)

        assert isinstance(markdown_content, str)
        assert len(markdown_content) > 0
        assert "# Python Programming Basics" in markdown_content
        assert "Learn Python programming from scratch" in markdown_content
        assert "## Learning Objectives" in markdown_content
        assert "Understand Python syntax" in markdown_content
        assert "## Week 1: Python Basics" in markdown_content

    def test_course_json_to_markdown_with_template(self):
        """Test JSON to Markdown conversion with template"""
        # This should use the Jinja2 template if available
        markdown_content = course_json_to_markdown(self.mock_course_data)

        # Check for template-specific content
        assert "Generated by CourseCraft-AI" in markdown_content

    def test_course_json_to_markdown_fallback(self):
        """Test fallback Markdown generation when template fails"""
        # Test with minimal data that might cause template to fail
        minimal_data = {
            "title": "Test Course",
            "description": "Test Description",
            "duration_weeks": 1,
            "learning_objectives": ["Objective 1"],
            "prerequisites": ["Prerequisite 1"],
            "weeks": []
        }

        markdown_content = course_json_to_markdown(minimal_data)

        assert isinstance(markdown_content, str)
        assert "# Test Course" in markdown_content
        assert "Test Description" in markdown_content

    def test_markdown_to_html_basic(self):
        """Test basic Markdown to HTML conversion"""
        markdown_content = """
# Test Course

## Learning Objectives
- Objective 1
- Objective 2

## Week 1: Basics
Content here.
"""

        html_content = markdown_to_html(markdown_content)

        assert isinstance(html_content, str)
        assert len(html_content) > 0
        assert "<html>" in html_content
        assert "<body>" in html_content
        assert "<h1>Test Course</h1>" in html_content
        assert "<h2>Learning Objectives</h2>" in html_content
        assert "<ul>" in html_content
        assert "<li>Objective 1</li>" in html_content

    def test_markdown_to_html_styling(self):
        """Test HTML conversion includes CSS styling"""
        markdown_content = "# Test Course\n\nContent here."

        html_content = markdown_to_html(markdown_content)

        assert "<style>" in html_content
        assert "font-family:" in html_content
        assert "color: #333;" in html_content
        assert ".footer" in html_content

    def test_markdown_to_html_fallback(self):
        """Test fallback HTML generation when conversion fails"""
        # Test with problematic markdown
        problematic_content = None

        html_content = markdown_to_html(problematic_content)

        assert isinstance(html_content, str)
        assert "<pre>" in html_content

    def test_save_pdf_file_with_weasyprint(self):
        """Test saving PDF file with WeasyPrint"""
        html_content = "<html><body><h1>Test Course</h1></body></html>"

        with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as temp_file:
            temp_path = temp_file.name

        try:
            # Mock WeasyPrint import to simulate successful conversion
            with patch('app.services.pdf_service.HTML') as mock_html:
                mock_instance = MagicMock()
                mock_html.return_value = mock_instance

                result = save_pdf_file(html_content, temp_path)

                assert result is True
                assert os.path.exists(temp_path)

        except ImportError:
            # WeasyPrint not available, test fallback
            result = save_pdf_file(html_content, temp_path)
            assert result is True
            assert os.path.exists(temp_path)

            # Check that it's an HTML file (fallback)
            with open(temp_path, 'r') as f:
                content = f.read()
                assert "<html>" in content

        finally:
            # Clean up
            if os.path.exists(temp_path):
                os.unlink(temp_path)

    def test_save_pdf_file_fallback(self):
        """Test fallback PDF saving when WeasyPrint is not available"""
        html_content = "<html><body><h1>Test Course</h1></body></html>"

        with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as temp_file:
            temp_path = temp_file.name

        try:
            # Simulate WeasyPrint import error
            with patch('app.services.pdf_service.HTML', side_effect=ImportError):
                result = save_pdf_file(html_content, temp_path)

                assert result is True
                assert os.path.exists(temp_path)

                # Check that it's an HTML file
                with open(temp_path, 'r') as f:
                    content = f.read()
                    assert "<html>" in content

        finally:
            # Clean up
            if os.path.exists(temp_path):
                os.unlink(temp_path)

    def test_generate_course_pdf_basic(self):
        """Test basic course PDF generation"""
        with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as temp_file:
            temp_path = temp_file.name

        try:
            result = generate_course_pdf(self.mock_course_data, temp_path)

            assert result is True
            assert os.path.exists(temp_path)
            assert os.path.getsize(temp_path) > 0

        finally:
            # Clean up
            if os.path.exists(temp_path):
                os.unlink(temp_path)

    def test_generate_course_pdf_empty_data(self):
        """Test PDF generation with empty course data"""
        with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as temp_file:
            temp_path = temp_file.name

        try:
            result = generate_course_pdf({}, temp_path)

            assert result is False

        finally:
            # Clean up
            if os.path.exists(temp_path):
                os.unlink(temp_path)

    def test_generate_course_pdf_directory_creation(self):
        """Test PDF generation creates directories if needed"""
        # Test path that doesn't exist
        test_dir = "test_output_dir"
        test_path = os.path.join(test_dir, "test_course.pdf")

        try:
            # Remove directory if it exists
            if os.path.exists(test_dir):
                import shutil
                shutil.rmtree(test_dir)

            # This should create the directory and save the file
            result = generate_course_pdf(self.mock_course_data, test_path)

            assert result is True
            assert os.path.exists(test_path)
            assert os.path.exists(test_dir)  # Directory should be created

        finally:
            # Clean up
            if os.path.exists(test_path):
                os.unlink(test_path)
            if os.path.exists(test_dir):
                import shutil
                shutil.rmtree(test_dir)

    def test_markdown_content_structure(self):
        """Test that generated Markdown has proper structure"""
        markdown_content = course_json_to_markdown(self.mock_course_data)

        # Check for required sections
        required_sections = [
            "# Python Programming Basics",
            "## Learning Objectives",
            "## Prerequisites",
            "## Week 1: Python Basics",
            "### Day 1: Introduction to Python",
            "## Assignments",
            "## Flashcards",
            "## Course Completion"
        ]

        for section in required_sections:
            assert section in markdown_content

    def test_html_content_structure(self):
        """Test that generated HTML has proper structure"""
        markdown_content = course_json_to_markdown(self.mock_course_data)
        html_content = markdown_to_html(markdown_content)

        # Check for required HTML elements
        required_elements = [
            "<html>",
            "<head>",
            "<title>",
            "<body>",
            "</html>",
            "Generated by CourseCraft-AI"
        ]

        for element in required_elements:
            assert element in html_content

    def test_pdf_generation_error_handling(self):
        """Test PDF generation error handling"""
        # Test with invalid file path
        invalid_path = "/invalid/path/that/does/not/exist/course.pdf"

        result = generate_course_pdf(self.mock_course_data, invalid_path)

        assert result is False

    def test_markdown_fallback_generation(self):
        """Test fallback Markdown generation function"""
        from app.services.pdf_service import _fallback_markdown_generation

        minimal_data = {
            "title": "Test Course",
            "description": "Test Description",
            "difficulty": "beginner",
            "duration_weeks": 1,
            "learning_objectives": ["Learn something"],
            "prerequisites": ["Basic knowledge"],
            "weeks": []
        }

        markdown_content = _fallback_markdown_generation(minimal_data)

        assert isinstance(markdown_content, str)
        assert "# Test Course" in markdown_content
        assert "Test Description" in markdown_content
        assert "Learning Objectives" in markdown_content

    def test_html_styling_inclusion(self):
        """Test that HTML includes proper CSS styling"""
        markdown_content = "# Test\n\nContent"
        html_content = markdown_to_html(markdown_content)

        # Check for CSS styles
        css_elements = [
            "font-family:",
            "color:",
            "background-color:",
            "margin:",
            "padding:"
        ]

        for element in css_elements:
            assert element in html_content

    def test_pdf_file_format(self):
        """Test that generated PDF files have correct format"""
        with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as temp_file:
            temp_path = temp_file.name

        try:
            result = generate_course_pdf(self.mock_course_data, temp_path)

            if result:
                # Check file properties
                assert os.path.exists(temp_path)
                file_size = os.path.getsize(temp_path)
                assert file_size > 0

                # File should be readable
                with open(temp_path, 'rb') as f:
                    content = f.read()
                    assert len(content) == file_size

        finally:
            # Clean up
            if os.path.exists(temp_path):
                os.unlink(temp_path)

    def test_course_data_validation_in_pdf_generation(self):
        """Test that PDF generation validates course data"""
        # Test with missing required fields
        incomplete_data = {
            "title": "Test Course"
            # Missing other required fields
        }

        with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as temp_file:
            temp_path = temp_file.name

        try:
            result = generate_course_pdf(incomplete_data, temp_path)

            # Should still work with fallback generation
            assert isinstance(result, bool)

        finally:
            # Clean up
            if os.path.exists(temp_path):
                os.unlink(temp_path)